import type { Metadata } from "next";
import { Allura, Google_Sans } from "next/font/google";
import "./globals.css";

const allura = Allura({
  variable: "--font-allura",

  weight: ["400"],
  preload: true,
});

const googleSans = Google_Sans({
  variable: "--font-google-sans",
  subsets: ["latin"],
  weight: ["400", "500", "600"],
  preload: true,
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${allura.variable} ${googleSans.variable} antialiased`}>
        {children}
      </body>
    </html>
  );
}
